Collections:
  - Name: AUTOFORMER
    Metadata:
      Training Data:
        - ImageNet-1k
    Paper:
      URL: https://arxiv.org/abs/2107.00651
      Title: Searching Transformers for Visual Recognition
    README: configs/nas/mmcls/autoformer/README.md
    Code:
      URL: https://github.com/open-mmlab/mmrazor/blob/dev-1.x/mmrazor/models/algorithms/nas/autoformer.py
      Version: V1.0.0rc2

Models:
  - Name: autoformer_subnet_8xb256_in1k
    In Collection: AUTOFORMER
    Metadata:
      Flops(G): 10.57
      Params(M): 54.319
      Subnet: https://github.com/open-mmlab/mmrazor/blob/dev-1.x/configs/nas/mmcls/autoformer/AUTOFORMER_SUBNET_B.yaml
    Results:
      - Task: Image Classification
        Dataset: ImageNet-1k
        Metrics:
          Top 1 Accuracy: 82.47
    Config: configs/nas/mmcls/autoformer/autoformer_subnet_8xb256_in1k.py
    Weights: https://download.openmmlab.com/mmrazor/v1/autoformer/autoformer_supernet_32xb256_in1k_20220919_110144-c658ce8f.pth
