Collections:
  - Name: FBKD
    Metadata:
      Training Data:
        - COCO
    Paper:
      URL: https://openreview.net/pdf?id=uKhGRvM8QNH
      Title: IMPROVE OBJECT DETECTION WITH FEATURE-BASED KNOWLEDGE DISTILLATION- TOWARDS ACCURATE AND EFFICIENT DETECTORS
    README: configs/distill/mmdet/fbkd/README.md
    Converted From:
      Code:
        URL: https://github.com/ArchipLab-LinfengZhang/Object-Detection-Knowledge-Distillation-ICLR2021
Models:
  - Name: fbkd_fpn_faster-rcnn_resnet101_faster-rcnn_resnet50_1x_coco
    In Collection: FBKD
    Metadata:
      Location: fpn
      Student:
        Metrics:
          box AP: 37.4
        Config: mmdet::faster_rcnn/faster-rcnn_r50_fpn_1x_coco.py
        Weights: https://download.openmmlab.com/mmdetection/v2.0/faster_rcnn/faster_rcnn_r50_fpn_1x_coco/faster_rcnn_r50_fpn_1x_coco_20200130-047c8118.pth
      Teacher:
        Metrics:
          box AP: 39.4
        Config: mmdet::faster_rcnn/faster-rcnn_r101_fpn_1x_coco.py
        Weights: https://download.openmmlab.com/mmdetection/v2.0/faster_rcnn/faster_rcnn_r101_fpn_1x_coco/faster_rcnn_r101_fpn_1x_coco_20200130-f513f705.pth
    Results:
      - Task: Object Detection
        Dataset: COCO
        Metrics:
          box AP: 39.1
    Config: configs/distill/mmdet/fbkd/fbkd_fpn_faster-rcnn_resnet101_faster-rcnn_resnet50_1x_coco.py
    Weights:
