Collections:
  - Name: Darts
    Metadata:
      Training Data:
        - CIFAR-10
    Paper:
      URL: https://arxiv.org/abs/1806.09055
      Title: DARTS:Differentiable Architecture Search
    README: configs/nas/mmcls/darts/README.md
    Code:
      URL: https://github.com/open-mmlab/mmrazor/blob/v0.1.0/mmrazor/models/algorithms/darts.py
      Version: v0.1.0
    Converted From:
      Code: https://github.com/quark0/darts
Models:
  - Name: darts_subnet_1xb96_cifar10_2.0
    In Collection: Darts
    Metadata:
      Params(M): 3.42
      Mutable: https://download.openmmlab.com/mmrazor/v0.1/nas/darts/darts_subnetnet_1xb96_cifar10/darts_subnetnet_1xb96_cifar10_acc-97.32_20211222-e5727921_mutable_cfg.yaml
    Results:
      - Task: Image Classification
        Dataset: CIFAR-10
        Metrics:
          Top 1 Accuracy: 97.32
          Top 5 Accuracy: 99.94
    Config: configs/nas/darts/darts_subnet_1xb96_cifar10_2.0.py
    Weights: https://download.openmmlab.com/mmrazor/v0.1/nas/darts/darts_subnetnet_1xb96_cifar10/darts_subnetnet_1xb96_cifar10_acc-97.32_20211222-e5727921.pth
