backbone.conv1.bn:
  out_channels: 8
  raw_out_channels: 48
backbone.conv1.conv:
  in_channels: 3
  out_channels: 8
  raw_in_channels: 3
  raw_out_channels: 48
backbone.conv2.bn:
  out_channels: 1920
  raw_out_channels: 1920
backbone.conv2.conv:
  in_channels: 480
  out_channels: 1920
  raw_in_channels: 480
  raw_out_channels: 1920
backbone.layer1.0.conv.0.bn:
  out_channels: 8
  raw_out_channels: 48
backbone.layer1.0.conv.0.conv:
  in_channels: 8
  out_channels: 8
  raw_in_channels: 48
  raw_out_channels: 48
backbone.layer1.0.conv.1.bn:
  out_channels: 8
  raw_out_channels: 24
backbone.layer1.0.conv.1.conv:
  in_channels: 8
  out_channels: 8
  raw_in_channels: 48
  raw_out_channels: 24
backbone.layer2.0.conv.0.bn:
  out_channels: 96
  raw_out_channels: 144
backbone.layer2.0.conv.0.conv:
  in_channels: 8
  out_channels: 96
  raw_in_channels: 24
  raw_out_channels: 144
backbone.layer2.0.conv.1.bn:
  out_channels: 96
  raw_out_channels: 144
backbone.layer2.0.conv.1.conv:
  in_channels: 96
  out_channels: 96
  raw_in_channels: 144
  raw_out_channels: 144
backbone.layer2.0.conv.2.bn:
  out_channels: 16
  raw_out_channels: 40
backbone.layer2.0.conv.2.conv:
  in_channels: 96
  out_channels: 16
  raw_in_channels: 144
  raw_out_channels: 40
backbone.layer2.1.conv.0.bn:
  out_channels: 96
  raw_out_channels: 240
backbone.layer2.1.conv.0.conv:
  in_channels: 16
  out_channels: 96
  raw_in_channels: 40
  raw_out_channels: 240
backbone.layer2.1.conv.1.bn:
  out_channels: 96
  raw_out_channels: 240
backbone.layer2.1.conv.1.conv:
  in_channels: 96
  out_channels: 96
  raw_in_channels: 240
  raw_out_channels: 240
backbone.layer2.1.conv.2.bn:
  out_channels: 16
  raw_out_channels: 40
backbone.layer2.1.conv.2.conv:
  in_channels: 96
  out_channels: 16
  raw_in_channels: 240
  raw_out_channels: 40
backbone.layer3.0.conv.0.bn:
  out_channels: 96
  raw_out_channels: 240
backbone.layer3.0.conv.0.conv:
  in_channels: 16
  out_channels: 96
  raw_in_channels: 40
  raw_out_channels: 240
backbone.layer3.0.conv.1.bn:
  out_channels: 96
  raw_out_channels: 240
backbone.layer3.0.conv.1.conv:
  in_channels: 96
  out_channels: 96
  raw_in_channels: 240
  raw_out_channels: 240
backbone.layer3.0.conv.2.bn:
  out_channels: 24
  raw_out_channels: 48
backbone.layer3.0.conv.2.conv:
  in_channels: 96
  out_channels: 24
  raw_in_channels: 240
  raw_out_channels: 48
backbone.layer3.1.conv.0.bn:
  out_channels: 144
  raw_out_channels: 288
backbone.layer3.1.conv.0.conv:
  in_channels: 24
  out_channels: 144
  raw_in_channels: 48
  raw_out_channels: 288
backbone.layer3.1.conv.1.bn:
  out_channels: 144
  raw_out_channels: 288
backbone.layer3.1.conv.1.conv:
  in_channels: 144
  out_channels: 144
  raw_in_channels: 288
  raw_out_channels: 288
backbone.layer3.1.conv.2.bn:
  out_channels: 24
  raw_out_channels: 48
backbone.layer3.1.conv.2.conv:
  in_channels: 144
  out_channels: 24
  raw_in_channels: 288
  raw_out_channels: 48
backbone.layer3.2.conv.0.bn:
  out_channels: 144
  raw_out_channels: 288
backbone.layer3.2.conv.0.conv:
  in_channels: 24
  out_channels: 144
  raw_in_channels: 48
  raw_out_channels: 288
backbone.layer3.2.conv.1.bn:
  out_channels: 144
  raw_out_channels: 288
backbone.layer3.2.conv.1.conv:
  in_channels: 144
  out_channels: 144
  raw_in_channels: 288
  raw_out_channels: 288
backbone.layer3.2.conv.2.bn:
  out_channels: 24
  raw_out_channels: 48
backbone.layer3.2.conv.2.conv:
  in_channels: 144
  out_channels: 24
  raw_in_channels: 288
  raw_out_channels: 48
backbone.layer4.0.conv.0.bn:
  out_channels: 144
  raw_out_channels: 288
backbone.layer4.0.conv.0.conv:
  in_channels: 24
  out_channels: 144
  raw_in_channels: 48
  raw_out_channels: 288
backbone.layer4.0.conv.1.bn:
  out_channels: 144
  raw_out_channels: 288
backbone.layer4.0.conv.1.conv:
  in_channels: 144
  out_channels: 144
  raw_in_channels: 288
  raw_out_channels: 288
backbone.layer4.0.conv.2.bn:
  out_channels: 56
  raw_out_channels: 96
backbone.layer4.0.conv.2.conv:
  in_channels: 144
  out_channels: 56
  raw_in_channels: 288
  raw_out_channels: 96
backbone.layer4.1.conv.0.bn:
  out_channels: 288
  raw_out_channels: 576
backbone.layer4.1.conv.0.conv:
  in_channels: 56
  out_channels: 288
  raw_in_channels: 96
  raw_out_channels: 576
backbone.layer4.1.conv.1.bn:
  out_channels: 288
  raw_out_channels: 576
backbone.layer4.1.conv.1.conv:
  in_channels: 288
  out_channels: 288
  raw_in_channels: 576
  raw_out_channels: 576
backbone.layer4.1.conv.2.bn:
  out_channels: 56
  raw_out_channels: 96
backbone.layer4.1.conv.2.conv:
  in_channels: 288
  out_channels: 56
  raw_in_channels: 576
  raw_out_channels: 96
backbone.layer4.2.conv.0.bn:
  out_channels: 288
  raw_out_channels: 576
backbone.layer4.2.conv.0.conv:
  in_channels: 56
  out_channels: 288
  raw_in_channels: 96
  raw_out_channels: 576
backbone.layer4.2.conv.1.bn:
  out_channels: 288
  raw_out_channels: 576
backbone.layer4.2.conv.1.conv:
  in_channels: 288
  out_channels: 288
  raw_in_channels: 576
  raw_out_channels: 576
backbone.layer4.2.conv.2.bn:
  out_channels: 56
  raw_out_channels: 96
backbone.layer4.2.conv.2.conv:
  in_channels: 288
  out_channels: 56
  raw_in_channels: 576
  raw_out_channels: 96
backbone.layer4.3.conv.0.bn:
  out_channels: 288
  raw_out_channels: 576
backbone.layer4.3.conv.0.conv:
  in_channels: 56
  out_channels: 288
  raw_in_channels: 96
  raw_out_channels: 576
backbone.layer4.3.conv.1.bn:
  out_channels: 288
  raw_out_channels: 576
backbone.layer4.3.conv.1.conv:
  in_channels: 288
  out_channels: 288
  raw_in_channels: 576
  raw_out_channels: 576
backbone.layer4.3.conv.2.bn:
  out_channels: 56
  raw_out_channels: 96
backbone.layer4.3.conv.2.conv:
  in_channels: 288
  out_channels: 56
  raw_in_channels: 576
  raw_out_channels: 96
backbone.layer5.0.conv.0.bn:
  out_channels: 288
  raw_out_channels: 576
backbone.layer5.0.conv.0.conv:
  in_channels: 56
  out_channels: 288
  raw_in_channels: 96
  raw_out_channels: 576
backbone.layer5.0.conv.1.bn:
  out_channels: 288
  raw_out_channels: 576
backbone.layer5.0.conv.1.conv:
  in_channels: 288
  out_channels: 288
  raw_in_channels: 576
  raw_out_channels: 576
backbone.layer5.0.conv.2.bn:
  out_channels: 96
  raw_out_channels: 144
backbone.layer5.0.conv.2.conv:
  in_channels: 288
  out_channels: 96
  raw_in_channels: 576
  raw_out_channels: 144
backbone.layer5.1.conv.0.bn:
  out_channels: 432
  raw_out_channels: 864
backbone.layer5.1.conv.0.conv:
  in_channels: 96
  out_channels: 432
  raw_in_channels: 144
  raw_out_channels: 864
backbone.layer5.1.conv.1.bn:
  out_channels: 432
  raw_out_channels: 864
backbone.layer5.1.conv.1.conv:
  in_channels: 432
  out_channels: 432
  raw_in_channels: 864
  raw_out_channels: 864
backbone.layer5.1.conv.2.bn:
  out_channels: 96
  raw_out_channels: 144
backbone.layer5.1.conv.2.conv:
  in_channels: 432
  out_channels: 96
  raw_in_channels: 864
  raw_out_channels: 144
backbone.layer5.2.conv.0.bn:
  out_channels: 432
  raw_out_channels: 864
backbone.layer5.2.conv.0.conv:
  in_channels: 96
  out_channels: 432
  raw_in_channels: 144
  raw_out_channels: 864
backbone.layer5.2.conv.1.bn:
  out_channels: 432
  raw_out_channels: 864
backbone.layer5.2.conv.1.conv:
  in_channels: 432
  out_channels: 432
  raw_in_channels: 864
  raw_out_channels: 864
backbone.layer5.2.conv.2.bn:
  out_channels: 96
  raw_out_channels: 144
backbone.layer5.2.conv.2.conv:
  in_channels: 432
  out_channels: 96
  raw_in_channels: 864
  raw_out_channels: 144
backbone.layer6.0.conv.0.bn:
  out_channels: 864
  raw_out_channels: 864
backbone.layer6.0.conv.0.conv:
  in_channels: 96
  out_channels: 864
  raw_in_channels: 144
  raw_out_channels: 864
backbone.layer6.0.conv.1.bn:
  out_channels: 864
  raw_out_channels: 864
backbone.layer6.0.conv.1.conv:
  in_channels: 864
  out_channels: 864
  raw_in_channels: 864
  raw_out_channels: 864
backbone.layer6.0.conv.2.bn:
  out_channels: 240
  raw_out_channels: 240
backbone.layer6.0.conv.2.conv:
  in_channels: 864
  out_channels: 240
  raw_in_channels: 864
  raw_out_channels: 240
backbone.layer6.1.conv.0.bn:
  out_channels: 1440
  raw_out_channels: 1440
backbone.layer6.1.conv.0.conv:
  in_channels: 240
  out_channels: 1440
  raw_in_channels: 240
  raw_out_channels: 1440
backbone.layer6.1.conv.1.bn:
  out_channels: 1440
  raw_out_channels: 1440
backbone.layer6.1.conv.1.conv:
  in_channels: 1440
  out_channels: 1440
  raw_in_channels: 1440
  raw_out_channels: 1440
backbone.layer6.1.conv.2.bn:
  out_channels: 240
  raw_out_channels: 240
backbone.layer6.1.conv.2.conv:
  in_channels: 1440
  out_channels: 240
  raw_in_channels: 1440
  raw_out_channels: 240
backbone.layer6.2.conv.0.bn:
  out_channels: 960
  raw_out_channels: 1440
backbone.layer6.2.conv.0.conv:
  in_channels: 240
  out_channels: 960
  raw_in_channels: 240
  raw_out_channels: 1440
backbone.layer6.2.conv.1.bn:
  out_channels: 960
  raw_out_channels: 1440
backbone.layer6.2.conv.1.conv:
  in_channels: 960
  out_channels: 960
  raw_in_channels: 1440
  raw_out_channels: 1440
backbone.layer6.2.conv.2.bn:
  out_channels: 240
  raw_out_channels: 240
backbone.layer6.2.conv.2.conv:
  in_channels: 960
  out_channels: 240
  raw_in_channels: 1440
  raw_out_channels: 240
backbone.layer7.0.conv.0.bn:
  out_channels: 1440
  raw_out_channels: 1440
backbone.layer7.0.conv.0.conv:
  in_channels: 240
  out_channels: 1440
  raw_in_channels: 240
  raw_out_channels: 1440
backbone.layer7.0.conv.1.bn:
  out_channels: 1440
  raw_out_channels: 1440
backbone.layer7.0.conv.1.conv:
  in_channels: 1440
  out_channels: 1440
  raw_in_channels: 1440
  raw_out_channels: 1440
backbone.layer7.0.conv.2.bn:
  out_channels: 480
  raw_out_channels: 480
backbone.layer7.0.conv.2.conv:
  in_channels: 1440
  out_channels: 480
  raw_in_channels: 1440
  raw_out_channels: 480
head.fc:
  in_channels: 1920
  out_channels: 1000
  raw_in_channels: 1920
  raw_out_channels: 1000
