Collections:
  - Name: ABLoss
    Metadata:
      Training Data:
        - ImageNet-1k
    Paper:
      URL: https://arxiv.org/pdf/1811.03233.pdf
      Title: Knowledge Transfer via Distillation of Activation Boundaries Formed by Hidden Neurons
    README: configs/distill/mmcls/abloss/README.md
    Converted From:
      Code:
        URL: https://github.com/bhheo/AB_distillation
Models:
  - Name: abloss_logits_resnet50_resnet18_8xb32_in1k
    In Collection: ABLoss
    Metadata:
      Location: logits
      Student:
        Config: mmcls::resnet/resnet18_8xb32_in1k.py
        Weights: https://download.openmmlab.com/mmclassification/v0/resnet/resnet18_8xb32_in1k_20210831-fbbb1da6.pth
        Metrics:
          Top 1 Accuracy: 69.90
          Top 5 Accuracy: 89.43
      Teacher:
        Config: mmcls::resnet/resnet50_8xb32_in1k.py
        Weights: https://download.openmmlab.com/mmclassification/v0/resnet/resnet50_8xb32_in1k_20210831-ea4938fc.pth
        Metrics:
          Top 1 Accuracy: 76.55
          Top 5 Accuracy: 93.06
    Results:
      - Task: Image Classification
        Dataset: ImageNet-1k
        Metrics:
          Top 1 Accuracy: 69.94
    Config: configs/distill/mmcls/abloss/abloss_logits_resnet50_resnet18_8xb32_in1k.py
    Weights: https://download.openmmlab.com/mmrazor/v1/ABLoss/abloss_logits_resnet50_resnet18_8xb32_in1k_20220830_202129-f35edde8.pth
