Collections:
  - Name: DetNAS
    Metadata:
      Training Data:
        - ImageNet-1k
        - COCO
    Paper:
      URL: https://arxiv.org/abs/1903.10979
      Title: DetNAS:Backbone Search for Object Detection
    README: configs/nas/mmdet/detnas/README.md
    Code:
      URL: https://github.com/open-mmlab/mmrazor/blob/v0.1.0/mmrazor/models/algorithms/detnas.py
      Version: v0.1.0
    Converted From:
      Code: https://github.com/megvii-model/DetNAS
Models:
  - Name: detnas_frcnn_shufflenet_subnet_coco_1x
    In Collection: DetNAS
    Metadata:
      FLOPs(Backbone): 340 MB
      Params(Backbone): 3.35 MB
      Supernet: FRCNN-ShuffleNetV2
      Mutable: https://download.openmmlab.com/mmrazor/v1/detnas/detnas_subnet_frcnn_shufflenetv2_fpn_1x_coco_bbox_backbone_flops-0.34M_mAP-37.5_20220715-61d2e900_subnet_cfg_v1.yaml
    Results:
      - Task: Object Detection
        Dataset: COCO
        Metrics:
          box AP: 37.5
    Config: configs/nas/mmdet/detnas/detnas_frcnn_shufflenet_subnet_coco_1x.py
    Weights: https://download.openmmlab.com/mmrazor/v1/detnas/detnas_subnet_frcnn_shufflenetv2_fpn_1x_coco_bbox_backbone_flops-0.34M_mAP-37.5_20220715-61d2e900_v1.pth
