Collections:
  - Name: CWD
    Metadata:
      Training Data:
        - Cityscapes
        - COCO
    Paper:
      URL: https://arxiv.org/abs/2011.13256
      Title: Channel-wise Knowledge Distillation for Dense Prediction
    README: configs/distill/cwd/README.md
    Code:
      URL: https://github.com/open-mmlab/mmrazor/blob/v0.1.0/mmrazor/models/losses/cwd.py#L10
      Version: v0.1.0
    Converted From:
      Code:
        - https://github.com/pppppM/mmsegmentation-distiller
        - https://github.com/pppppM/mmdetection-distiller
Models:
  - Name: cwd_cls_head_pspnet_r101_d8_pspnet_r18_d8_512x1024_cityscapes_80k
    In Collection: CWD
    Metadata:
      Location: cls head
      Student: pspnet-r18-d8
      Teacher: pspnet-r101-d8
      Teacher Checkpoint: https://download.openmmlab.com/mmsegmentation/v0.5/pspnet/pspnet_r101-d8_512x1024_80k_cityscapes/pspnet_r101-d8_512x1024_80k_cityscapes_20200606_112211-e1e1100f.pth
    Results:
      - Task: Semantic Segmentation
        Dataset: Cityscapes
        Metrics:
          mIoU: 75.54
          mIoU(S): 74.87
          mIoU(T): 79.76
    Config: configs/distill/cwd/cwd_cls_head_pspnet_r101_d8_pspnet_r18_d8_512x1024_cityscapes_80k.py
    Weights: https://download.openmmlab.com/mmrazor/v0.1/distill/cwd/cwd_cls_head_pspnet_r101_d8_pspnet_r18_d8_512x1024_cityscapes_80k/cwd_cls_head_pspnet_r101_d8_pspnet_r18_d8_512x1024_cityscapes_80k_mIoU-75.54_20211222-3a26ee1c.pth
  - Name: cwd_cls_head_gfl_r101_fpn_gfl_r50_fpn_1x_coco
    In Collection: CWD
    Metadata:
      Location: cls head
      Student: gfl-r50-fpn
      Teacher: gfl-r101-fpn
      Teacher Checkpoint: https://download.openmmlab.com/mmdetection/v2.0/gfl/gfl_r101_fpn_mstrain_2x_coco/gfl_r101_fpn_mstrain_2x_coco_20200629_200126-dd12f847.pth
    Results:
      - Task: Object Detection
        Dataset: COCO
        Metrics:
          box AP: 41.9
          box AP(S): 40.2
          box AP(T): 44.7
    Config: configs/distill/cwd/cwd_cls_head_gfl_r101_fpn_gfl_r50_fpn_1x_coco.py
    Weights: https://download.openmmlab.com/mmrazor/v0.1/distill/cwd/cwd_cls_head_gfl_r101_fpn_gfl_r50_fpn_1x_coco/cwd_cls_head_gfl_r101_fpn_gfl_r50_fpn_1x_coco_20211222-655dff39.pth
