Collections:
  - Name: MGD
    Metadata:
      Training Data:
        - COCO
    Paper:
      URL: https://arxiv.org/abs/2205.01529
      Title: Masked Generative Distillation
    README: configs/distill/mmdet/mgd/README.md

Models:
  - Name: mgd_fpn_retina_x101_retina_r50_2x_coco
    In Collection: MGD
    Metadata:
      Location: FPN
      Student:
        Metrics:
          box AP: 37.4
        Config: mmdet::retinanet/retinanet_r50_fpn_2x_coco.py
        Weights: https://download.openmmlab.com/mmdetection/v2.0/retinanet/retinanet_r50_fpn_2x_coco/retinanet_r50_fpn_2x_coco_20200131-fdb43119.pth
      Teacher:
        Metrics:
          box AP: 41.0
        Config: mmdet::retinanet/retinanet_x101-64x4d_fpn_1x_coco.py
        Weights: https://download.openmmlab.com/mmdetection/v2.0/retinanet/retinanet_x101_64x4d_fpn_1x_coco/retinanet_x101_64x4d_fpn_1x_coco_20200130-366f5af1.pth
    Results:
      - Task: Object Detection
        Dataset: COCO
        Metrics:
          box AP: 41.0
    Config: configs/distill/mmdet/mgd/mgd_fpn_retina_x101_retina_r50_2x_coco.py
    Weights: https://download.openmmlab.com/mmrazor/v1/mgd/mgd_fpn_retina_x101_retina_r50_2x_coco_20221209_191847-87141529.pth
