Collections:
  - Name: ZSKT
    Metadata:
      Training Data:
        - CIFAR-10
    Paper:
      URL: https://arxiv.org/abs/1905.09768
      Title: Zero-shot Knowledge Transfer via Adversarial Belief Matching
    README: configs/distill/mmcls/zskt/README.md
    Converted From:
      Code:
        URL: https://github.com/polo5/ZeroShotKnowledgeTransfer
Models:
  - Name: zskt_backbone_logits_resnet34_resnet18_8xb16_cifar10
    In Collection: ZSKT
    Metadata:
      inference time (ms/im):
        - value: 0.12
          hardware: NVIDIA A100-SXM4-80GB
          backend: PyTorch
          batch size: 16
          mode: FP32
          resolution: (32, 32)
      Location: backbone & logits
      Student:
        Config: mmcls::resnet/resnet18_8xb16_cifar10.py
        Weights: https://download.openmmlab.com/mmclassification/v0/resnet/resnet18_b16x8_cifar10_20210528-bd6371c8.pth
        Metrics:
          Top 1 Accuracy: 94.82
          Top 5 Accuracy: 99.87
      Teacher:
        Config: mmcls::resnet/resnet34_8xb16_cifar10.py
        Weights: https://download.openmmlab.com/mmclassification/v0/resnet/resnet34_b16x8_cifar10_20210528-a8aa36a6.pth
        Metrics:
          Top 1 Accuracy: 95.34
          Top 5 Accuracy: 99.87
    Results:
      - Task: Image Classification
        Dataset: CIFAR-10
        Metrics:
          Top 1 Accuracy: 93.05
    Config: configs/distill/mmcls/zskt/zskt_backbone_logits_resnet34_resnet18_8xb16_cifar10.py
    Weights: https://download.openmmlab.com/mmrazor/v1/ZSKT/zskt_backbone_logits_resnet34_resnet18_8xb16_cifar10_20220823_114006-28584c2e.pth
