Collections:
  - Name: DSNAS
    Metadata:
      Training Data:
        - ImageNet-1k
    Paper:
      URL: https://arxiv.org/abs/2002.09128.pdf
      Title: DSNAS Direct Neural Architecture Search without Parameter Retraining
    README: configs/nas/mmcls/dsnas/README.md
    Code:
      URL: https://github.com/open-mmlab/mmrazor/blob/dev-1.x/mmrazor/models/algorithms/nas/dsnas.py
      Version: V1.0.0rc2

Models:
  - Name: dsnas_subnet_8xb128_in1k
    In Collection: DSNAS
    Metadata:
      Flops(G): 0.299
      Params(M): 3.33
      Subnet: https://github.com/open-mmlab/mmrazor/blob/dev-1.x/configs/nas/mmcls/dsnas/DSNAS_SUBNET_IMAGENET_PAPER_ALIAS.yaml
    Results:
      - Task: Image Classification
        Dataset: ImageNet-1k
        Metrics:
          Top 1 Accuracy: 73.56
    Config: configs/nas/mmcls/dsnas/dsnas_subnet_8xb128_in1k.py
    Weights: https://download.openmmlab.com/mmrazor/v1/dsnas/dsnas_supernet_8xb128_in1k_20220926_171954-29b87e3a.pth
